# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtidy" do
  desc "A terminal UI app to clean up development dependencies and build artifacts."
  homepage "https://github.com/dunkbing/devtidy"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtidy"

  on_macos do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.5/devtidy_Darwin_x86_64.tar.gz"
      sha256 "9758cd9c8c4de5926d3940e1001fbc0b3efdae30834d728a6762d6d81456da7e"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.5/devtidy_Darwin_arm64.tar.gz"
      sha256 "0d1ace6a3bd24c0f0c1bb084c08f70f76eb62b3c2445912809c30f1dab4d05a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.5/devtidy_Linux_x86_64.tar.gz"
      sha256 "15ff747a1b713e3393d962ee4b193718f8dd57bf2a6c832e9665db3873c3642f"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.5/devtidy_Linux_arm64.tar.gz"
      sha256 "4574d18f0eb48fd18d78e92fcc48c960398ceb30515ef52f89c2515250814d9b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devtidy"]
    end
  end

  # No zap stanza required
end
