# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtidy" do
  desc "A terminal UI app to clean up development dependencies and build artifacts."
  homepage "https://github.com/dunkbing/devtidy"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtidy"

  on_macos do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.3/devtidy_Darwin_x86_64.tar.gz"
      sha256 "87f074cc192a9552d777373d31eaa2f3de68fad4ba28cce6e5f35c15840d783e"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.3/devtidy_Darwin_arm64.tar.gz"
      sha256 "6dcfdd4b0d2c6e3045adfe5c31649ea3d02e23d277a5b3e3d0e94bb094dc68dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.3/devtidy_Linux_x86_64.tar.gz"
      sha256 "6f01d08c2d7dbaa846c23c7da75a0ef3e3ad5105ca84a5e44bf7b5c16ac068b5"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.3/devtidy_Linux_arm64.tar.gz"
      sha256 "96c84b5d2a14855b729e00831c76d34ce5aacebf1a8737579e02239caed7f5a4"
    end
  end

  # No zap stanza required
end
