# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtidy" do
  desc "A terminal UI app to clean up development dependencies and build artifacts."
  homepage "https://github.com/dunkbing/devtidy"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtidy"

  on_macos do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.2/devtidy_Darwin_x86_64.tar.gz"
      sha256 "b8ac1d85fec5aae4f5b50cf6fb47e4d5c64334a32c17b078fc1bc560e77a87e4"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.2/devtidy_Darwin_arm64.tar.gz"
      sha256 "b4c7d18d158a0b7c2f881fb0cbab7896590e61ebd0f67f439769caff259d5ff0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.2/devtidy_Linux_x86_64.tar.gz"
      sha256 "8f34308d2d61f73c7364867f3efdc792f9d7ec2bbb9aea3f46290b9ad4fc7429"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.2/devtidy_Linux_arm64.tar.gz"
      sha256 "0681d9a193ce98e81851903c33cfdecbd485b0c71c8cc4c32d56cb221d16965a"
    end
  end

  # No zap stanza required
end
