# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtidy" do
  desc "A terminal UI app to clean up development dependencies and build artifacts."
  homepage "https://github.com/dunkbing/devtidy"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtidy"

  on_macos do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.1/devtidy_Darwin_x86_64.tar.gz"
      sha256 "c4f4a7a3f00bcbb6671449639b9f69e378435fd259be02066fea1d33e84833ae"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.1/devtidy_Darwin_arm64.tar.gz"
      sha256 "c1ef57e941d27979bc82372928537a5cb88007ad9233b11e7e4a084a57cf5543"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.1/devtidy_Linux_x86_64.tar.gz"
      sha256 "547087680305cc3373c496089c75a4a10cde564044e9e4fb4f947f7fcac63599"
    end
    on_arm do
      url "https://github.com/dunkbing/devtidy/releases/download/v1.0.1/devtidy_Linux_arm64.tar.gz"
      sha256 "ecae79f8e6003f7c1db2a03475e2e7396bfde8b8177dc468ce5a5272da6e4086"
    end
  end

  # No zap stanza required
end
