# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kana < Formula
  desc "Terminal app to practice Kana"
  homepage "https://github.com/dunkbing/kana"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/dunkbing/kana/releases/download/v0.3.0/kana_Darwin_x86_64.tar.gz"
      sha256 "6ba1314efdc1a441a1684a1bc4504c56256ec120eeedf79abd92c263b531f6be"

      def install
        bin.install "kana"
      end
    end
    on_arm do
      url "https://github.com/dunkbing/kana/releases/download/v0.3.0/kana_Darwin_arm64.tar.gz"
      sha256 "3ee94bf6dae440f87c7c0ddfdac3913fb12d63cd07afef5e664330ec60c43424"

      def install
        bin.install "kana"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dunkbing/kana/releases/download/v0.3.0/kana_Linux_x86_64.tar.gz"
        sha256 "8a003fabf3bd29f5bda4805b32dd6d4e9d3ef08d11e24ae944a06c94de310d4d"

        def install
          bin.install "kana"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dunkbing/kana/releases/download/v0.3.0/kana_Linux_arm64.tar.gz"
        sha256 "25f34dff389eb026882e922726ef1544a00f3c56d31d42f51877696856253c1f"

        def install
          bin.install "kana"
        end
      end
    end
  end

  test do
    system "#{bin}/kana --help"
  end
end
