# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kana < Formula
  desc "Terminal app to practice Kana"
  homepage "https://github.com/dunkbing/kana"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dunkbing/kana/releases/download/v0.1.0/kana_Darwin_x86_64.tar.gz"
      sha256 "1340626ef2976f00fe2f73c4da187e587760c20c55cfedf0f0d1d9551cc9fb33"

      def install
        bin.install "kana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dunkbing/kana/releases/download/v0.1.0/kana_Darwin_arm64.tar.gz"
      sha256 "a7853d328decc4d758836d6488f1f3776042e6734d6e38109b7bfe6d2c63b538"

      def install
        bin.install "kana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dunkbing/kana/releases/download/v0.1.0/kana_Linux_x86_64.tar.gz"
      sha256 "1c1bffb3f9b3deb8f44fef541330acd91bb4ef76b27c1acf09f883d9901efd0f"

      def install
        bin.install "kana"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dunkbing/kana/releases/download/v0.1.0/kana_Linux_arm64.tar.gz"
      sha256 "28bbc4a45c724d0b9899716991258bdec71f89ddd64963890c09f553be6bd838"

      def install
        bin.install "kana"
      end
    end
  end

  test do
    system "#{bin}/kana --help"
  end
end
